name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use the token
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        echo $MY_TOKEN





name: Python CI

on: [push]

jobs:
  test:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use the token
      env:
        MY_TOKEN: ${{ secrets.MYTOKEN }}
      run: |
        echo $MYTOKEN
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icalendar ics requests
    - name: Run script
      run: |
        python run1.py
