name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Generate file
      run: |
        echo "This is a test file." > 123.txt
        
    - name: List files
      run: |
        ls
    - name: Run Python script
      run: python run1.py
