name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List files in directory
      run: |
        ls
        
    - name: Output a message
      run: |
        echo "Hello, world!"
